[package]
name = "SBHacksIV_Server"
version = "0.1.0"
authors = ["Samuel Resendez <saresend@usc.edu>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
reqwest = "0.8.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tesseract = "0.1.0"
